### ISSUE TITLE
Php-Error in config\setup\Header.php

### ISSUE THREAD

**Issue by Ortimis** [Alecaddd/awps#10]
Fatal error: Using $this when not in object context in C:\wamp64\www\ortimis-wp\wp-content\themes\ortimis\config\setup\Header.php on line 42

**Comment by Alecaddd** [comment]
Thanks for the report, I'm on it!

**Comment by Alecaddd** [comment]
Hi, are you still having this issue?
Are you sure you pulled the most recent version? The `Header()` class gets instantiated properly os the `$this` can be used without issues.

**Comment by Ortimis** [comment]
Haven't tested your recent release. But there is the same problem with a copy of the theme that I am currently working with.

**Comment by CamelKing** [comment]
My editor (VS Code) highlighted that "$this->header_text_color" as error in header.php as well.

Running the code seems to be OK. Is it better to use self:: ?

**Comment by Alecaddd** [comment]
I just released `v3.0.1` which removes that file and delegates the customization of the Header to the Customizer.
Closing this issue.
