### ISSUE TITLE
Misspelling + Gulp issues

### ISSUE THREAD

**Issue by tysian** [Alecaddd/awps#13]
First of all - I'm beginner in wordpress themes developing, so also a beginner in AWPS.

## Misspell
awps/config/Custom/Admin.php => private function enqueue()
```php
$scripts = array(
	'script' => array( 
		'jquery', 
		'media_uplaoder',
		get_template_directory_uri() . '/assets/js/admin.min.js'
	),
```
Shouldn't it be _media_uploader_?
I also had to change a _jquery_ into `get_template_directory_uri() . '/node_modules/jquery/dist/jquery.js`, because jquery in admin.js didn't worked for me.

## Gulp watch issue
When I run `gulp watch`, it watches files, and fires compilation on every change, even If I didn't save changes.

- Visual Studio Code version 1.19.2 
- I'm running watch via built-in terminal on Windows 10 Pro with Ubuntu Bash

It happens also, if I run standalone terminal and use (for example) Atom.
It's not very disturbing, but If I'm during writing some code, gulp throw error compilation and stops watching.
```
[Browsersync] 4 files changed (style.min.css.map, style.min.css, admin.min.css.map, admin.min.css)
[Browsersync] 2 files changed (admin.min.js.map, admin.min.js)
[Browsersync] Reloading Browsers... (buffered 6 events)
[Browsersync] 2 files changed (main.min.js.map, main.min.js)
[Browsersync] Reloading Browsers... (buffered 2 events)
[13:51:07] Starting 'js'...
[13:51:07] Finished 'js' after 2.49 ms
events.js:163
      throw er; // Unhandled 'error' event
      ^

SyntaxError: /mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/src/scripts/admin.js: Unexpected token (3:28)
  1 | $(document).ready(()=>{
  2 |     let str = $('#togglesInput').val();
> 3 |     let arr = str.substring(.split(',');
    |                             ^
  4 |     console.log(arr);
  5 | });
    at Parser.pp$5.raise (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/mnt/d/xampp/htdocs/wordpress/wp-content/themes/bazgier/node_modules/babylon/lib/index.js:3573:20)
```
As you can see, I've changed some code, then I stopped (yay, I need to think what I should do next), and gulp stops working, I had to start it again by `gulp watch`.
## Gulp https issue
I had also problem with browser-sync and https. I had to create my own certs, but chrome still throws website is unsecured.
```javascript
gulp.task( 'browser-sync', function() {
	browserSync.init({
		proxy: projectURL,
		https: {
			key: '/Users/alecaddd/.valet/Certificates/wp.dev.key',
			cert: '/Users/alecaddd/.valet/Certificates/wp.dev.crt'
		},
		injectChanges: true,
		open: false
	});
});
```

**Comment by Alecaddd** [comment]
Hi, thank you so much for using AWPS and this detailed report!

### Misspell
Indeed, that's an error, I will push a fix later today.

### Gulp Watch
I set Gulp to compile all the files even if you just trigger watch, it's better to bundle and build the assets as soon as Gulp gets triggered, it doesn't matter if you didn't do any changes.

Gulp stops when it encounters an error in your code and is telling you where is the mistake.
You wrote something wrong in your admin.js here:
```
let arr = str.substring(.split(',');
```
You can't use the `.split()` method without attaching it to a variable or string. Fix your code and Gulp won't crash.

### Gulp HTTPS
If you created your own local certs, can you access your local URL with HTTPS?
Did you properly update the PATHS to point to your own local certificates?
Google bought the `.dev` domains and if it's not secured, will not work, even if it's local.
Try to open it in Firefox.

Let me know

**Comment by tysian** [comment]
Thanks for fast reply and amazing YouTube tutorials!

## Gulp watch
I wrote everything okay, but gulp compiled everything before I've ended typing my code.
Can I change setting of watcher to **compile on file save**, not on file change **OR** gulp don't stop when compile error?

## Gulp HTTPS
Yeah, PATHS are updated to my own, so there are no console errors anymore.
I'm using XAMPP, and standard `http://localhost` proxy
```
[Browsersync] Proxying: https://localhost
[Browsersync] Access URLs:
 ------------------------------------------------
       Local: https://localhost:3000/wordpress
    External: https://192.168.1.11:3000/wordpress
 ------------------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.11:3001
 ------------------------------------------------
```
Browsersync works fine for me, but each browser says, the connection is not safe.
Maybe it's because I'm newbie in creating _https://_ connections, so I've done something wrong in ssl setup (I was trying to run code from [this tutorial](https://deliciousbrains.com/https-locally-without-browser-privacy-errors/)).

**Comment by Alecaddd** [comment]
Oh, so Gulp compiles without you saving your file?
After you triggered `gulp watch` wait for it to compile everything, and when it's done and watching, start typing some edits.
Gulp watch, after it runs for the first time, should only trigger itself when you save a file. That's the default behavior.
Unfortunately, Gulp will stop when it encounters an error.

For the HTTPS issue, I never used XAMPP, so I'm not sure I know what's the problem nd how to fix it.

**Comment by tysian** [comment]
Fixed gulp by turning off autosave in text editors.
HTTPS issue is not a big problem, just 2 more clicks.
