### ISSUE TITLE
Improving test

### ISSUE THREAD

**Issue by szepeviktor** [Alecaddd/awps#16]
Please consider

- [x] Getting testing tools (JS/PHP) from package managers (require-dev)
- [x] Compile [JSX](https://github.com/Alecaddd/awps/blob/master/assets/src/scripts/blocks/hello-world.js#L32-L37) before running jshint - breaks tests
- [x] SNIFF=1 could be done the Travis-way, if you are about running tests only in one of the jobs, move before-script to the matrix

**Comment by Alecaddd** [comment]
Would you be interested in making a PR to take care of some of these?

**Comment by Alecaddd** [comment]
I'll start implementing some PHP unit tests

**Comment by szepeviktor** [comment]
@Alecaddd How about moving jscs and jshing into packages.json?
And making current devdeps into deps?

**Comment by Alecaddd** [comment]
I'm currently working on the `dev` branch to transition to `eslint` and use dependencies from the package.json file.

**Comment by szepeviktor** [comment]
OK!!

**Comment by szepeviktor** [comment]
@Alecaddd It is done: https://travis-ci.org/Alecaddd/awps/jobs/415176283
only a typescript problem.
Does it suite you?

**Comment by Alecaddd** [comment]
I implemented `eslint` and finally the travis build is passing 😬

**Comment by szepeviktor** [comment]
I think it is *done*
