### ISSUE TITLE
SASS Structure

### ISSUE THREAD

**Issue by bahiirwa** [Alecaddd/awps#17]
Hello Alecaddd,

I love the work flow and was inquiring if you have a plan of using a css structure like [ITCSS](https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/). The one in AWPS is simple and usable but could be simpler and easier to learn. Your thoughts? Oh this could be part of your documentation for question other future users might ask ;-)  

Reference: https://github.com/Automattic/_s/issues/1215

**Comment by Alecaddd** [comment]
Thanks for using AWPS and for the suggestion.
I'm not planning to do anything particular with the SASS structure as the one I built it's just a really small starter configuration.
I don't want to tie AWPS to a specific structure as the main purpose of AWPS is to be a barebone starter point for everyone to modify and build on top.
Thanks anyway 😄
