### ISSUE TITLE
Laravel Mix Versioning

### ISSUE THREAD

**Issue by Ortimis** [Alecaddd/awps#18]
I love the workflow and have used it on several production sites now.

Being there, I ran into the problem of cache busting and would therefore suggest to implement the versioning of laravel mix.

This would also mean that we have to add the mix(); function of laraval mix and adjust the file paths accordingly. See this [gist](https://gist.github.com/Ortimis/b9a727422fc7586153f97f7db3109077)

**Comment by Ortimis** [comment]
In additition extracting a vendor.js for used libraries would also make sense.

If you have any doubts about this, please tell me now. I would otherwise propose a PR in the next days.

**Comment by Alecaddd** [comment]
Nice suggestion, and definitely a worthy implementation.
Go ahead and submit a PR, thanks

**Comment by Ortimis** [comment]
#19
