### ISSUE TITLE
How I can add Shortcodes to my theme?

### ISSUE THREAD

**Issue by rjfortis7** [Alecaddd/awps#20]
Hello Alecaddd,

In this path: awps/inc/Custom/Custom.php how I can create and add Shortcodes to my theme?

**Comment by Ortimis** [comment]
This is not a question specific to this starter theme.
Look Here: https://codex.wordpress.org/Shortcode_API

**Comment by Alecaddd** [comment]
Also, check my plugin development series, where I explained how to create ShortCode in a OOP structure.
