### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by generer** [Alecaddd/awps#3]
I hit a problem, can you help?

C:\workspace\websites\wpawps\wp-content\themes>awps new sunny

Summoning application..
Downloading Package..

[GuzzleHttp\Exception\RequestException]
cURL error 60: SSL certificate problem: unable to get local issuer certific
ate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

new

**Comment by Alecaddd** [comment]
Check this link, I think a user had your exact same problem and solved it in this way.
https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/replies/37017

**Comment by Alecaddd** [comment]
I will close this issue because it's not related to the theme, but to GuzzleHttps and its package version
