### ISSUE TITLE
Woocommerce review is not showing. 

### ISSUE THREAD

**Issue by pulla** [Alecaddd/awps#32]
Is there any reason that woocommerce review is not showing. just showing a normal comment.
Enabled all options to be able to WooCommerce review.

Thank you,

**Comment by pulla** [comment]
Hello Alecadd, 

Did you have time to have a look? Somehow review session in WC is not showing? did you add any code to hide it? 
I switched themes to WP default and others. They show properly. But not AWPS.

Thank you,

**Comment by Alecaddd** [comment]
I'm sorry, I didn't have time to check this issue. I should be able to confirm it and fix it next week.
Thanks for the report.

**Comment by NeverDev** [comment]
For Woocommerce 3 I remember uou need to have this line in your theme

`add_theme_support( 'woocommerce' );`

I will make a PL Soon with this. Hope this will save you
