### ISSUE TITLE
withAPIData deprecated

### ISSUE THREAD

**Issue by bahiirwa** [Alecaddd/awps#34]
In development of blocks, wp.components.withAPIData has been removed. Please use the Core Data module or wp.apiFetch directly instead. https://wordpress.org/gutenberg/handbook/reference/deprecated/#3-7-0

**Comment by bahiirwa** [comment]
This is for Gutenberg v3.7.0+ Check the latest posts block

**Comment by Alecaddd** [comment]
Thanks for the issue, I will find some time to update it

**Comment by bahiirwa** [comment]
I have shared a solution in https://github.com/Alecaddd/awps/pull/38
