### ISSUE TITLE
javascript double slash in path

### ISSUE THREAD

**Issue by andreapaiola** [Alecaddd/awps#35]
after "assets/dist"

dev:
wp-content/themes/awps/assets/dist//js/app.js?ver=1.0.0'></script>

prod:
wp-content/themes/awps/assets/dist//js/app.js?id=08a4e7a767d06618d6ef&#038;ver=1.0.0'></script>

**Comment by Alecaddd** [comment]
Oh, thanks for the heads up.
It should be an issue coming from the `Helpers.php` file in the `mix()` method.
Updating line 57 to:
```
$manifestDirectory = "assets/dist";
```
should fix it. I'll test it later and push an update.

**Comment by andreapaiola** [comment]
ok thanks

same for css

<link rel='stylesheet' id='main-css'  href='wp-content/themes/awps/assets/dist//css/style.css?id=6e6be2f36a11396ca7fd&#038;ver=1.0.0' type='text/css' media='all' />
