### ISSUE TITLE
jquery undefined and boostrap undefined.

### ISSUE THREAD

**Issue by pulla** [Alecaddd/awps#39]
I have added boostrap js, scss files.

But it shows undefined for inline scripts.
I think it places on footer. So I added global define autoload.

mix.autoload({
	jquery: ['$', 'window.jQuery', "jQuery", "window.$", "jquery", "window.jquery"],
	'popper.js/dist/umd/popper.js': ['Popper']
});

But it doesn't work. 

I have searched on google and tried many ways. But inline scripts are all undefined. 

Can you please add an example how to add boostrap4?

Thank you,

**Comment by syonrod** [comment]
@pulla something similar happen to me with Jquery, i'm trying to use the Query Monitor plugin and i got this alert:
 _
> A JavaScript problem on the page is preventing Query Monitor from working correctly. jQuery may have been blocked from loading.
_

did you find the way to fix this?

**Comment by Alecaddd** [comment]
Try using this:

```
mix.autoload({
  jquery: ['$', 'window.jQuery', 'jQuery'],
});
```
