### ISSUE TITLE
How is the WalkerNav Class used?

### ISSUE THREAD

**Issue by SamThilmany** [Alecaddd/awps#40]
After adding some pages to the primary menu, I inspected the output in my browser. 

The following HTML is sent to the browser.

```
<div class="menu-main-menu-container">
    <ul id="primary-menu" class="menu">
        <li id="menu-item-37" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-37"><a href="https://www.sathil-starter-theme.dev/home/">Home</a></li>
         <li id="menu-item-34" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-34"><a href="https://www.sathil-starter-theme.dev/about/">About</a></li>
         <li id="menu-item-35" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-35"><a href="https://www.sathil-starter-theme.dev/contact/">Contact</a></li>
     </ul>
</div>
```

Now I'm wondering why the bootstrap classes that you already implemented to the `WalkerNav` Class are not in the output. The `WalkerNav` for example should return the following for the opening `ul`: `<ul class=\"dropdown-menu$submenu depth_$depth\" >`. As you can see there is, however, no class named `dropdown-menu*`.

What am I missing?

---

PS: I'm using the current `awps` version and have not edited any of the files that are invoked in the output of the menu.

**Comment by Alecaddd** [comment]
As @NeverDev correctly stated, the dropdown class gets applied only on submenus.
You can edit the Walker class to make it fit your needs.
