### ISSUE TITLE
Testing wordpress v5 beta2

### ISSUE THREAD

**Issue by waterleat** [Alecaddd/awps#41]
Testing new gutenberg editor having it crash when saving a simple post. the first line of the error message is TypeError: Cannot read property 'addQueryArgs' of undefined
this error occurs in (also note the categories and tags dropdowns are not shown)
- an earlier v3 version of AWPS when using tailwindcss 13/04/2018
- the latest version of AWPS as downloaded 30/10/2018

However it does not do it in version 2 of AWPS 31/01/2018 

I started a query with wordpress at [https://wordpress.org/support/topic/gutenberg-giving-error-when-creating-new-post/]

**Comment by Alecaddd** [comment]
WordPress and Gutenberg are changing so drastically from release to release that I decided to stop fixing compatibility issues and wait for the final release of WordPress 5.

After that, I will fix AWPS and make it compatible with the latest Gutenberg APIs.
Cheers

**Comment by waterleat** [comment]
Thank you for all your work which has helped me greatly. There are not many people who give advanced code with quality explanations. I shall have a look at you new website when I have a free moment. 
Happy Life and Happy Coding!
