### ISSUE TITLE
Warnings and errors

### ISSUE THREAD

**Issue by vishalp36** [Alecaddd/awps#42]
1. Warning: dirname() expects exactly 1 parameter, 2 given in C:\wamp\www\awps\wp-content\themes\awps\inc\Helpers.php on line 66
2. Fatal error: Uncaught exception 'Exception' with message 'The Mix manifest does not exist.' in C:\wamp\www\awps\wp-content\themes\awps\inc\Helpers.php on line 73
3. Exception: The Mix manifest does not exist. in C:\wamp\www\awps\wp-content\themes\awps\inc\Helpers.php on line 73

**Comment by NeverDev** [comment]
Did you follow every step of the installation section ?

Installation
Move the .env.example to your WordPress root directory, rename it as .env, and setup your website variables
Move the wp-config.sample.php to your WordPress root directory and rename it as wp-config.php, to replace the default one
Open a Terminal window on the location of the theme folder
Execute composer install
Execute npm install

Then you will have to do this command to compile assets and generate the manifest.json file : npm run dev

**Comment by Alecaddd** [comment]
Also, which version of PHP are you running?
AWPS required PHP >= 7.2
