### ISSUE TITLE
TypeError: Cannot read property 'RichText' of undefined in gutenberg.js

### ISSUE THREAD

**Issue by akramk22** [Alecaddd/awps#46]
Hey Alecaddd,

Love the theme! Great work!

I'm having an issue with getting Gutenberg to work correctly when editing a page on the new Wordpress 5.0. The add new block button is disabled for me. Opening the console gives me an error.

Error:
`TypeError: Cannot read property 'RichText' of undefined`

The line `const { RichText, BlockControls, AlignmentToolbar } = wp.editor`

Changing wp.editor to wp.blocks removes the error but I still seem to have an issue with getting the add new block button to work properly. I'll keep digging and can hopefully find a solution. 

Can you reference the documentation for the API that you used. Since the one I found seems a bit different. 

Thanks!

**Comment by Alecaddd** [comment]
Hi, thank you so much for using AWPS and sorry for the issue.

I'm doing a round of fixes and I will push a new version soon as the Gutenberg API changed drastically in the latest versions.
I'll reference this issue once the new version is up

**Comment by Ortimis** [comment]
Is there an outlook on when a new version of awps is up?

**Comment by Alecaddd** [comment]
@Ortimis I'm releasing a new version with fully compatible Gutenberg blocks in 2 days
