### ISSUE TITLE
Unload module javascript file

### ISSUE THREAD

**Issue by andreapaiola** [Alecaddd/awps#53]
Hi,

how can I load 
wp-content/plugins/lightbox-photoswipe/js/frontend.min.js
?

The module is https://wordpress.org/plugins/lightbox-photoswipe/

`wp_enqueue_script(
            'photoswipe-lib',
            plugin_dir_url(__FILE__) . 'lib/photoswipe.min.js',
            array(),
            self::LIGHTBOX_PHOTOSWIPE_VERSION
);`

` wp_enqueue_script(
        'photoswipe-ui-default',
        plugin_dir_url(__FILE__) . 'lib/photoswipe-ui-default.min.js',
        array('photoswipe-lib'),
        self::LIGHTBOX_PHOTOSWIPE_VERSION
 );`

`wp_enqueue_script(
       'photoswipe-frontend',
        plugin_dir_url(__FILE__) . 'js/frontend.min.js',
        array('photoswipe-lib', 'photoswipe-ui-default', 'jquery'),
        self::LIGHTBOX_PHOTOSWIPE_VERSION
);`

photoswipe.min.js **is loaded**
photoswipe-ui-default.min.js **is loaded**
frontend.min.js **is not loaded**

`die(plugin_dir_url(__FILE__) . 'js/frontend.min.js');`

return https://site.local/wp-content/plugins/lightbox-photoswipe/js/frontend.min.js

which is right...

using another theme the js is loaded

Thank you!

**Comment by Alecaddd** [comment]
You declared `'jquery'` as dependency for the `frontend.min.js`.
In AWPS, by default, jQuery gets unregistered in the `Enqueue.php` file.
Remove that line or enqueue your local version of jQuery to make it work.
