### ISSUE TITLE
The site is experiencing technical difficulties while following awps

### ISSUE THREAD

**Issue by ranganbd1** [Alecaddd/awps#56]
Hi Alex,

I am following your tutorial https://www.youtube.com/watch?v=NKRheNMczlM&list=PLriKzYyLb28kvx7IVw2sAXtZ2yN4A1otJ&index=1

Upon installation I am seeing the following errors . 
No Idea, what I have done wrong !

Fatal error: Uncaught Exception: The Mix manifest does not exist. in /Applications/MAMP/community/mother/wp-content/themes/mother/inc/Helpers.php:74 Stack trace: #0 /Applications/MAMP/community/mother/wp-content/themes/mother/inc/Setup/Enqueue.php(33): mix('/css/style.css') #1 /Applications/MAMP/community/mother/wp-includes/class-wp-hook.php(286): mother\Setup\Enqueue->enqueue_scripts('') #2 /Applications/MAMP/community/mother/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /Applications/MAMP/community/mother/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /Applications/MAMP/community/mother/wp-includes/script-loader.php(2539): do_action('wp_enqueue_scri...') #5 /Applications/MAMP/community/mother/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts('') #6 /Applications/MAMP/community/mother/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #7 /Applications/MAMP/community/mother/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #8 /Applications/MAMP/communi in /Applications/MAMP/community/mother/wp-content/themes/mother/inc/Helpers.php on line 74
The site is experiencing technical difficulties.

Here is the screenshot : https://ibb.co/T8pT22h

**Comment by infinitodk** [comment]
You forgot to run npm run dev or npm run watch
