### ISSUE TITLE
Carousel css not loaded

### ISSUE THREAD

**Issue by BaronVonPerko** [Alecaddd/awps#58]
Not sure if this is intentional or not, but the css that ships with the slick carousel package isn't loaded into the theme, even though there is a *carousel.js* file.

In my project, I updated the mix file to include adding the css to the *assets* directory:

```javascript
mix.sass( 'node_modules/slick-carousel/slick/slick.scss', 'assets/dist/css' )
```

Then updated the *Enqueue.php* file:

```php
wp_enqueue_style( 'slick', mix('css/slick.css'), array(), '1.0.0', 'all' );
```

I can make a PR if you want this included by default 😉

**Comment by Alecaddd** [comment]
Yes please :smile: 
I should find some time to test AWPS with the new version of WP.
