### ISSUE TITLE
Fetal error on installing 

### ISSUE THREAD

**Issue by smEunus** [Alecaddd/awps#7]
I am getting an error

 "Fatal error: Uncaught Error: Class 'awps\core\tags' not found in /var/www/test/wp-content/themes/awps/views/content.php:23 Stack trace: #0 /var/www/test/wp-includes/template.php(690): require() #1 /var/www/test/wp-includes/template.php(647): load_template('/var/www/test/w...', false) #2 /var/www/test/wp-includes/general-template.php(167): locate_template(Array, true, false) #3 /var/www/test/wp-content/themes/awps/index.php(40): get_template_part('views/content', '') #4 /var/www/test/wp-includes/template-loader.php(74): include('/var/www/test/w...') #5 /var/www/test/wp-blog-header.php(19): require_once('/var/www/test/w...') #6 /var/www/test/index.php(17): require('/var/www/test/w...') #7 {main} thrown in /var/www/test/wp-content/themes/awps/views/content.php on line 23"

**Comment by Alecaddd** [comment]
Did you run `composer install` and followed the installation instructions?

**Comment by smEunus** [comment]
Oh!!!! Thanks for your reply.

**Comment by dme012** [comment]
Hello Alex! I am also getting this same error:


Daniel Estabillo

Just another WordPress site
Hello world!

Fatal error: Uncaught Error: Class 'Awps\Core\Tags' not found in /home/destabillo/Sites/daniel/wp-content/themes/estabillo/views/content.php:23 Stack trace: #0 /home/destabillo/Sites/daniel/wp-includes/template.php(690): require() #1 /home/destabillo/Sites/daniel/wp-includes/template.php(647): load_template('/home/destabill...', false) #2 /home/destabillo/Sites/daniel/wp-includes/general-template.php(167): locate_template(Array, true, false) #3 /home/destabillo/Sites/daniel/wp-content/themes/estabillo/index.php(40): get_template_part('views/content', '') #4 /home/destabillo/Sites/daniel/wp-includes/template-loader.php(74): include('/home/destabill...') #5 /home/destabillo/Sites/daniel/wp-blog-header.php(19): require_once('/home/destabill...') #6 /home/destabillo/Sites/daniel/index.php(17): require('/home/destabill...') #7 /home/destabillo/.config/composer/vendor/cpriego/valet-linux/server.php(203): require('/home/destabill...') #8 {main} thrown in /home/destabillo/Sites/daniel/wp-content/themes/estabillo/views/content.php on line 23
