### ISSUE TITLE
Usage with Local?

### ISSUE THREAD

**Issue by hirusi** [Alecaddd/awps#90]
Hello!

I used [Local](https://localwp.com/) to set up a development environment for myself. It sets up the required PHP version, the database, a WordPress instance, a local domain, and a local-only SSL certificate for the local domain.

Since all that is taken care of, what would my "installation" process look like? Any ideas here?

**Comment by Alecaddd** [comment]
Hi.
AWPS is just a theme, so you can simply download it in your themes folder and run `composer install` and `npm install` and you'll be good to go.
